/**
 * Clearcut area (ha) per region/sensor/year, served from a precomputed JSON file.
 *
 * The JSON at /data/clearcut_stats.json is generated by precompute_clearcut_stats.py
 * and has the shape:
 *   { "wabigoon_hls": { "2010": ha, … }, "wabigoon_planet": { "2025": ha }, … }
 *
 * Cache key: `${region}_${sensor}` — same convention as the old in-browser computation.
 */

import { DATA_BASE_URL } from '../config';

// Years that have Planet sensor data
export const CLEARCUT_PLANET_YEARS = [2025];

// Years whose tiles live under a sensor subfolder (hls/ or planet/)
export const CLEARCUT_SENSOR_SUBFOLDER_YEARS = [2025];

let _statsPromise = null;

function loadStats() {
  if (!_statsPromise) {
    _statsPromise = fetch(`${DATA_BASE_URL}/data/clearcut_stats.json`)
      .then(r => {
        if (!r.ok) throw new Error(`Failed to load clearcut_stats.json: ${r.status}`);
        return r.json();
      })
      .catch(err => {
        _statsPromise = null;
        throw err;
      });
  }
  return _statsPromise;
}

/**
 * Returns clearcut area in hectares for each year.
 *
 * @param {string} region
 * @param {number[]} years
 * @param {Function|null} onProgress - optional callback(year, areaHa) per year
 * @param {string} sensor - 'hls' or 'planet'
 * @returns {Promise<Object>} year → areaHa
 */
export async function computeClearcutAreaPerYear(region, years, onProgress, sensor = 'hls') {
  const all = await loadStats();
  const cacheKey = `${region}_${sensor}`;
  const byYear = all[cacheKey] ?? {};

  const results = {};
  for (const year of years) {
    const ha = byYear[String(year)] ?? 0;
    results[year] = ha;
    if (onProgress) onProgress(year, ha);
  }
  return results;
}

export function clearStatsCache() {
  _statsPromise = null;
}
